### ISSUE TITLE
unhandled error loading model iron_chivalrylance_raised

### ISSUE THREAD

**Issue by moderninity** [Magistu/Epic-Knights#18]
### Steps to Reproduce

I'm pretty new at reading logs so I apologize if it's wrong but have
[1.20.1-fabric]-Epic-Knights-8.2.jar
create-fabric-0.5.1-d-build.1161+mc1.20.1.jar
fabric-api-0.90.0+1.20.1.jar

not a full crash but get lag

### Expected Behavior

no processing lag from use.

### Actual Behavior

small lag bump

### Your Minecraft version

1.20.1 Fabric

### Your error log

https://mclo.gs/MWiZBco

### Additional Comments

Hope this helps!

```
[19:39:11] [Worker-ResourceReload-0/ERROR]: Unhandled error loading model: magistuarmory:item/iron_chivalrylance_raised
2054 | com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 34 column 2 path $
2055 | at com.google.gson.Gson.assertFullConsumption(Gson.java:1135) ~[gson-2.10.jar:?]
2056 | at com.google.gson.Gson.fromJson(Gson.java:1125) ~[gson-2.10.jar:?]
2057 | at com.google.gson.Gson.fromJson(Gson.java:1062) ~[gson-2.10.jar:?]
2058 | at io.github.fabricators_of_create.porting_lib.models.PortingLibModelLoadingRegistry$Resolver.resolveModel(PortingLibModelLoadingRegistry.java:63) ~[porting_lib_models-2.1.1127+1.20-94586d95bbeeb2d5.jar:?]
2059 | at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$0(ModelLoaderPluginContextImpl.java:57) ~[fabric-model-loading-api-v1-1.0.+709a987177-5cf784b70692b804.jar:?]
2060 | at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.resolveModel(ModelLoadingEventDispatcher.java:248) ~[fabric-model-loading-api-v1-1.0.+709a987177-5cf784b70692b804.jar:?]
2061 | at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.loadModel(ModelLoadingEventDispatcher.java:115) ~[fabric-model-loading-api-v1-1.0.+709a987177-5cf784b70692b804.jar:?]
2062 | at net.minecraft.client.render.model.ModelLoader.handler$ehf000$fabric-model-loading-api-v1$onLoadModel(ModelLoader.java:5145) ~[client-intermediary.jar:?]
2063 | at net.minecraft.class_1088.method_4715(class_1088.java) ~[client-intermediary.jar:?]
2064 | at net.minecraft.client.render.model.ModelLoader.getOrLoadModel(ModelLoader.java:256) ~[client-intermediary.jar:?]
2065 | at net.minecraft.client.render.model.ModelLoader.addModel(ModelLoader.java:389) ~[client-intermediary.jar:?]
2066 | at net.minecraft.client.render.model.ModelLoader.<init>(ModelLoader.java:173) ~[client-intermediary.jar:?]
2067 | at net.minecraft.client.render.model.BakedModelManager.method_45884(BakedModelManager.java:87) ~[client-intermediary.jar:?]
2068 | at net.minecraft.client.render.model.BakedModelManager.md2fb99c$fabric-model-loading-api-v1$lambda$loadModelPluginData$0$2(BakedModelManager.java:3579) ~[client-intermediary.jar:?]
2069 | at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311) ~[?:?]
2070 | at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280) ~[?:?]
2071 | at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
2072 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
2073 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
2074 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
2075 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
2076 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
2077 | Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 34 column 2 path $
2078 | at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
2079 | at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463) ~[gson-2.10.jar:?]
2080 | at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.jar:?]
2081 | at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar:?]
2082 | at com.google.gson.Gson.assertFullConsumption(Gson.java:1131) ~[gson-2.10.jar:?]
2083 | ... 21 more
2084 | [19:39:11] [Worker-ResourceReload-0/ERROR]: Failed to resolve model
2085 | com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 34 column 2 path $
2086 | at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[gson-2.10.jar:?]
2087 | at io.github.fabricators_of_create.porting_lib.models.obj.ObjLoader.tryLoadModelJson(ObjLoader.java:74) ~[porting_lib_obj_loader-2.1.1127+1.20-83f3abc8c90b9570.jar:?]
2088 | at io.github.fabricators_of_create.porting_lib.models.obj.ObjLoader$Resolver.lambda$resolveModel$2(ObjLoader.java:151) ~[porting_lib_obj_loader-2.1.1127+1.20-83f3abc8c90b9570.jar:?]
2089 | at java.util.Optional.map(Optional.java:260) ~[?:?]
2090 | at io.github.fabricators_of_create.porting_lib.models.obj.ObjLoader$Resolver.resolveModel(ObjLoader.java:150) ~[porting_lib_obj_loader-2.1.1127+1.20-83f3abc8c90b9570.jar:?]
2091 | at net.fabricmc.fabric.impl.client.model.loading.ModelLoaderPluginContextImpl.lambda$new$0(ModelLoaderPluginContextImpl.java:57) ~[fabric-model-loading-api-v1-1.0.+709a987177-5cf784b70692b804.jar:?]
2092 | at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.resolveModel(ModelLoadingEventDispatcher.java:248) ~[fabric-model-loading-api-v1-1.0.+709a987177-5cf784b70692b804.jar:?]
2093 | at net.fabricmc.fabric.impl.client.model.loading.ModelLoadingEventDispatcher.loadModel(ModelLoadingEventDispatcher.java:115) ~[fabric-model-loading-api-v1-1.0.+709a987177-5cf784b70692b804.jar:?]
2094 | at net.minecraft.client.render.model.ModelLoader.handler$ehf000$fabric-model-loading-api-v1$onLoadModel(ModelLoader.java:5145) ~[client-intermediary.jar:?]
2095 | at net.minecraft.class_1088.method_4715(class_1088.java) ~[client-intermediary.jar:?]
2096 | at net.minecraft.client.render.model.ModelLoader.getOrLoadModel(ModelLoader.java:256) ~[client-intermediary.jar:?]
2097 | at net.minecraft.client.render.model.ModelLoader.addModel(ModelLoader.java:389) ~[client-intermediary.jar:?]
2098 | at net.minecraft.client.render.model.ModelLoader.<init>(ModelLoader.java:173) ~[client-intermediary.jar:?]
2099 | at net.minecraft.client.render.model.BakedModelManager.method_45884(BakedModelManager.java:87) ~[client-intermediary.jar:?]
2100 | at net.minecraft.client.render.model.BakedModelManager.md2fb99c$fabric-model-loading-api-v1$lambda$loadModelPluginData$0$2(BakedModelManager.java:3579) ~[client-intermediary.jar:?]
2101 | at java.util.concurrent.CompletableFuture.biApply(CompletableFuture.java:1311) ~[?:?]
2102 | at java.util.concurrent.CompletableFuture$BiApply.tryFire(CompletableFuture.java:1280) ~[?:?]
2103 | at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?]
2104 | at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
2105 | at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
2106 | at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
2107 | at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
2108 | at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
2109 | Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 34 column 2 path $
2110 | at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1657) ~[gson-2.10.jar:?]
2111 | at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1463) ~[gson-2.10.jar:?]
2112 | at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[gson-2.10.jar:?]
2113 | at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[gson-2.10.jar:?]
2114 | at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[gson-2.10.jar:?]
2115 | ... 22 more
```

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
Thanks for the report, the exception doesn't appear since v8.7

**Comment by moderninity** [comment]
Ah gotcha, sorry, I was using latest version on modrinth
