### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SegoItCh** [Magistu/Epic-Knights#4]
[02:05:40] [Client thread/ERROR] [FML]: The mcmod.info file in [1.12.2]-Epic-Knights-Armor-and-Weapons-6.2v(uncomplete).jar cannot be parsed as valid JSON. It will be ignored
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.credits
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:952) ~[Gson.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:925) ~[Gson.class:?]
	at net.minecraftforge.fml.common.MetadataCollection.from(MetadataCollection.java:72) [MetadataCollection.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.discover(JarDiscoverer.java:65) [JarDiscoverer.class:?]
	at net.minecraftforge.fml.common.discovery.ContainerType.findMods(ContainerType.java:47) [ContainerType.class:?]
	at net.minecraftforge.fml.common.discovery.ModCandidate.explore(ModCandidate.java:74) [ModCandidate.class:?]
	at net.minecraftforge.fml.common.discovery.ModDiscoverer.identifyMods(ModDiscoverer.java:93) [ModDiscoverer.class:?]
	at net.minecraftforge.fml.common.Loader.identifyMods(Loader.java:427) [Loader.class:?]
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_362]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_362]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_362]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_362]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) [NewLaunch.jar:?]
Caused by: java.lang.IllegalStateException: Expected STRING but was BEGIN_ARRAY at path $.credits
	at com.google.gson.internal.bind.JsonTreeReader.nextString(JsonTreeReader.java:180) ~[JsonTreeReader.class:?]
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:418) ~[TypeAdapters$16.class:?]
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:406) ~[TypeAdapters$16.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[ReflectiveTypeAdapterFactory$1.class:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[ReflectiveTypeAdapterFactory$Adapter.class:?]
	... 23 more

**Comment by gwynhefar** [comment]
Having this same issue - was a fix ever found?
