### ISSUE TITLE
Laceration effect causing server crash

### ISSUE THREAD

**Issue by rx88xr** [Magistu/Epic-Knights#43]
### Steps to Reproduce

1. Open Minecraft Server; Join 
2. Enter a dungeon with custom mob spawner from "Dungeons Arise"
3. Within a minute or two, an entity will spawn causing the crash

Description: Ticking entity

java.lang.IllegalStateException: Unregistered holder in ResourceKey[minecraft:root / minecraft:mob_effect]: minecraft:mob_effect@magistuarmory:laceration
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar%23102!/:?] {re:mixin}
	at MC-BOOTSTRAP/datafixerupper@8.0.16/com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) ~[datafixerupper-8.0.16.jar%23102!/:?] {re:mixin}
	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.effect.MobEffectInstance.save(MobEffectInstance.java:318) ~[server-1.21.1-20240808.144430-srg.jar%23226!/:?] 

### Expected Behavior

No Crash

### Actual Behavior

Server crashing

### Your Minecraft version

1.21.1

### Your error log

https://gist.github.com/rx88xr/69a1661560e8b23d22a815d03a699551

### Conclusion

- [X] I agree that I am inattentively reading the description, just filling out everything

**Comment by Magistu** [comment]
duplicate of https://github.com/Magistu/Epic-Knights/issues/60
