### ISSUE TITLE
Laceration effect causing server crashes when applied to players

### ISSUE THREAD

**Issue by 1108-Harrel-Ben** [Magistu/Epic-Knights#45]
### Steps to Reproduce

1. equip a flame blade sword
2. strike another player

### Expected Behavior

damage dealt and laceration effect applied

### Actual Behavior

server host crash

### Your Minecraft version

fabric 1.21.1

### Your error log

---- Minecraft Crash Report ---- // Don't be sad, have a hug! <3  Time: 2024-12-07 16:01:28 Description: Saving entity NBT  java.lang.IllegalStateException: Unregistered holder in ResourceKey[minecraft:root / minecraft:mob_effect]: minecraft:mob_effect@magistuarmory:laceration 	at com.mojang.serialization.DataResult$Error.md49697d$owo$lambda$addStackTraceToException$0$0(DataResult.java:565) 	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) 	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) 	at net.minecraft.class_1293.method_5582(class_1293.java:311) 	at net.minecraft.class_1309.method_5652(class_1309.java:729) 	at net.minecraft.class_1657.method_5652(class_1657.java:893) 	at net.minecraft.class_3222.method_5652(class_3222.java:412) 	at net.minecraft.class_1297.method_5647(class_1297.java:1922) 	at net.minecraft.class_2105.method_9076(class_2105.java:39) 	at net.minecraft.class_2105.method_9072(class_2105.java:31) 	at net.minecraft.class_2048.method_8909(class_2048.java:189) 	at net.minecraft.class_215.method_914(class_215.java:39) 	at net.minecraft.class_215.test(class_215.java:16) 	at net.minecraft.class_5258.method_27806(class_5258.java:29) 	at net.minecraft.class_4558.method_22510(class_4558.java:61) 	at net.minecraft.class_2135.method_9141(class_2135.java:22) 	at net.minecraft.class_3222.method_5773(class_3222.java:554) 	at net.minecraft.class_3218.method_18762(class_3218.java:770) 	at net.minecraft.class_1937.method_18472(class_1937.java:498) 	at net.minecraft.class_3218.method_31420(class_3218.java:408) 	at net.minecraft.class_5574.method_31791(class_5574.java:54) 	at net.minecraft.class_3218.method_18765(class_3218.java:372) 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) 	at net.minecraft.class_1132.method_3748(class_1132.java:114) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) 	at java.base/java.lang.Thread.run(Thread.java:1583)   A detailed walkthrough of the error, its code path and all known details is as follows: ---------------------------------------------------------------------------------------  -- Head -- Thread: Render thread Stacktrace: 	at com.mojang.serialization.DataResult$Error.md49697d$owo$lambda$addStackTraceToException$0$0(DataResult.java:565) 	at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) 	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:81) 	at net.minecraft.class_1293.method_5582(class_1293.java:311) 	at net.minecraft.class_1309.method_5652(class_1309.java:729) 	at net.minecraft.class_1657.method_5652(class_1657.java:893) 	at net.minecraft.class_3222.method_5652(class_3222.java:412) 	at net.minecraft.class_1297.method_5647(class_1297.java:1922) 	at net.minecraft.class_2105.method_9076(class_2105.java:39) 	at net.minecraft.class_2105.method_9072(class_2105.java:31) 	at net.minecraft.class_2048.method_8909(class_2048.java:189) 	at net.minecraft.class_215.method_914(class_215.java:39) 	at net.minecraft.class_215.test(class_215.java:16) 	at net.minecraft.class_5258.method_27806(class_5258.java:29) 	at net.minecraft.class_4558.method_22510(class_4558.java:61) 	at net.minecraft.class_2135.method_9141(class_2135.java:22) 	at net.minecraft.class_3222.method_5773(class_3222.java:554) 	at net.minecraft.class_3218.method_18762(class_3218.java:770) 	at net.minecraft.class_1937.method_18472(class_1937.java:498) 	at net.minecraft.class_3218.method_31420(class_3218.java:408) 	at net.minecraft.class_5574.method_31791(class_5574.java:54)  -- Entity being saved -- Details: 	Entity Type: minecraft:player (net.minecraft.class_3222) 	Entity ID: 23 	Entity Name: xrendermanx 	Entity's Exact location: -666.09, 85.94, 710.27 	Entity's Block location: World: (-667,85,710), Section: (at 5,5,6 in -42,5,44; chunk contains blocks -672,-64,704 to -657,319,719), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023) 	Entity's Momentum: 0.00, -0.08, 0.00 	Entity's Passengers: [] 	Entity's Vehicle: null Stacktrace: 	at net.minecraft.class_1297.method_5647(class_1297.java:1922) 	at net.minecraft.class_2105.method_9076(class_2105.java:39) 	at net.minecraft.class_2105.method_9072(class_2105.java:31) 	at net.minecraft.class_2048.method_8909(class_2048.java:189) 	at net.minecraft.class_215.method_914(class_215.java:39) 	at net.minecraft.class_215.test(class_215.java:16) 	at net.minecraft.class_5258.method_27806(class_5258.java:29) 	at net.minecraft.class_4558.method_22510(class_4558.java:61) 	at net.minecraft.class_2135.method_9141(class_2135.java:22) 	at net.minecraft.class_3222.method_5773(class_3222.java:554) 	at net.minecraft.class_3218.method_18762(class_3218.java:770) 	at net.minecraft.class_1937.method_18472(class_1937.java:498) 	at net.minecraft.class_3218.method_31420(class_3218.java:408) 	at net.minecraft.class_5574.method_31791(class_5574.java:54) 	at net.minecraft.class_3218.method_18765(class_3218.java:372) 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) 	at net.minecraft.class_1132.method_3748(class_1132.java:114) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) 	at java.base/java.lang.Thread.run(Thread.java:1583)  -- Entity being ticked -- Details: 	Entity Type: minecraft:player (net.minecraft.class_3222) 	Entity ID: 23 	Entity Name: xrendermanx 	Entity's Exact location: -666.09, 85.94, 710.27 	Entity's Block location: World: (-667,85,710), Section: (at 5,5,6 in -42,5,44; chunk contains blocks -672,-64,704 to -657,319,719), Region: (-2,1; contains chunks -64,32 to -33,63, blocks -1024,-64,512 to -513,319,1023) 	Entity's Momentum: 0.00, -0.08, 0.00 	Entity's Passengers: [] 	Entity's Vehicle: null Stacktrace: 	at net.minecraft.class_1937.method_18472(class_1937.java:498) 	at net.minecraft.class_3218.method_31420(class_3218.java:408) 	at net.minecraft.class_5574.method_31791(class_5574.java:54) 	at net.minecraft.class_3218.method_18765(class_3218.java:372) 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1021) 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) 	at net.minecraft.class_1132.method_3748(class_1132.java:114) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) 	at java.base/java.lang.Thread.run(Thread.java:1583)  -- Affected level -- Details: 	All players: 2 total; [class_3222['xrendermanx'/23, l='ServerLevel[New World]', x=-666.09, y=85.94, z=710.27], class_3222['Goose_805'/891, l='ServerLevel[New World]', x=-666.09, y=85.94, z=707.62]] 	Chunk stats: 6427 	Level dimension: minecraft:overworld 	Level spawn location: World: (126,70,88), Section: (at 14,6,8 in 7,4,5; chunk contains blocks 112,-64,80 to 127,319,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511) 	Level time: 3924688 game time, 4993304 day time 	Level name: New World 	Level game mode: Game mode: survival (ID 0). Hardcore: false. Commands: true 	Level weather: Rain time: 39460 (now: false), thunder time: 89868 (now: false) 	Known server brands: fabric 	Removed feature flags:  	Level was modded: true 	Level storage version: 0x04ABD - Anvil 	Loaded entity count: 792 Stacktrace: 	at net.minecraft.class_3218.method_8538(class_3218.java:1693) 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1024) 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) 	at net.minecraft.class_1132.method_3748(class_1132.java:114) 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) 	at java.base/java.lang.Thread.run(Thread.java:1583)  -- System Details -- Details: 	Minecraft Version: 1.21.1 	Minecraft Version ID: 1.21.1 	Operating System: Windows 11 (amd64) version 10.0 	Java Version: 21.0.4, Oracle Corporation 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation 	Memory: 965492888 bytes (920 MiB) / 5217714176 bytes (4976 MiB) up to 34359738368 bytes (32768 MiB) 	CPUs: 32 	Processor Vendor: AuthenticAMD 	Processor Name: AMD Ryzen 9 3950X 16-Core Processor             	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0 	Microarchitecture: Zen 2 	Frequency (GHz): 3.50 	Number of physical packages: 1 	Number of physical CPUs: 16 	Number of logical CPUs: 32 	Graphics card #0 name: NVIDIA GeForce RTX 3090 	Graphics card #0 vendor: NVIDIA 	Graphics card #0 VRAM (MiB): 24576.00 	Graphics card #0 deviceId: VideoController1 	Graphics card #0 versionInfo: 32.0.15.6590 	Graphics card #1 name: NVIDIA GeForce RTX 3090 	Graphics card #1 vendor: NVIDIA 	Graphics card #1 VRAM (MiB): 24576.00 	Graphics card #1 deviceId: VideoController2 	Graphics card #1 versionInfo: 32.0.15.6590 	Graphics card #2 name: NVIDIA GeForce RTX 3090 	Graphics card #2 vendor: NVIDIA 	Graphics card #2 VRAM (MiB): 24576.00 	Graphics card #2 deviceId: VideoController3 	Graphics card #2 versionInfo: 32.0.15.6590 	Memory slot #0 capacity (MiB): 32768.00 	Memory slot #0 clockSpeed (GHz): 3.20 	Memory slot #0 type: DDR4 	Memory slot #1 capacity (MiB): 32768.00 	Memory slot #1 clockSpeed (GHz): 3.20 	Memory slot #1 type: DDR4 	Memory slot #2 capacity (MiB): 32768.00 	Memory slot #2 clockSpeed (GHz): 3.20 	Memory slot #2 type: DDR4 	Memory slot #3 capacity (MiB): 32768.00 	Memory slot #3 clockSpeed (GHz): 3.20 	Memory slot #3 type: DDR4 	Virtual memory max (MiB): 139169.78 	Virtual memory used (MiB): 27747.74 	Swap memory total (MiB): 8192.00 	Swap memory used (MiB): 0.00 	Space in storage for jna.tmpdir (MiB): <path not set> 	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): <path not set> 	Space in storage for io.netty.native.workdir (MiB): <path not set> 	Space in storage for java.io.tmpdir (MiB): available: 566379.31, total: 952983.00 	Space in storage for workdir (MiB): available: 566379.31, total: 952983.00 	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx32768m 	Fabric Mods:  		appleskin: AppleSkin 3.0.5+mc1.21 		architectury: Architectury 13.0.8 		areas: Areas 6.0 		armor-indicator: Armor Indicator 4.0.1+1.21 			alternate-hudrendercallback: Alternate HudRenderCallback 1.0.0 		armorful: Armorful 3.1.3+1.21 		balm-fabric: Balm 21.0.20 			kuma_api: KumaAPI 21.0.5-SNAPSHOT 		bclib: BCLib 21.0.13 		bettercombat: Better Combat 2.0.3+1.21.1 		betterend: Better End 21.0.11 		carryon: Carry On 2.2.2 		chat_heads: Chat Heads 0.13.0 		cicada: CICADA 0.9.1+1.21-1.21.1 		clientsort: ClientSort 0.9.0 		cloth-config: Cloth Config v15 15.0.140 			cloth-basic-math: cloth-basic-math 0.6.1 		collective: Collective 7.87 		combat-plus-core: Combat+ Core 3.1.0+1.21 			lilylib: LilyLib 1.3.0+1.21 		configurable-raids: Configurable Raids 1.0.2 		coroutil: CoroUtil 1.21.0-1.3.7 		cristellib: Cristel Lib 1.2.8 			blue_endless_jankson: jankson 1.2.3 		cupboard: cupboard 1.21-2.7 		dailydad_server: Daily Dad (Server) 2.0.2 		debugify: Debugify 1.21.1+1.0 		deeperdarker: Deeper and Darker 1.3.2.1 			customportalapi: Custom Portal Api 0.0.1-beta66-1.21 		do_a_barrel_roll: Do a Barrel Roll 3.7.2 			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT 			mixinsquared: MixinSquared 0.1.2-beta.4 		dualswords: Dual Swords 2.0.0+1.21 		elementa: Elementa 665 		elytraslot: Elytra Slot 9.0.1+1.21.1 		entityculling: EntityCulling 1.7.0 		essential: Essential 1.3.4.1 		essential-container: essential-container 1.0.0 			essential-loader: essential-loader 1.2.3 		explorerscompass: Explorer's Compass 1.21.1-2.2.5-fabric 		fabric-api: Fabric API 0.110.0+1.21.1 			fabric-api-base: Fabric API Base 0.4.42+6573ed8c19 			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.70+b559734419 			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.30+be1ed2d719 			fabric-block-api-v1: Fabric Block API (v1) 1.0.22+0af3f5a719 			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.10+6573ed8c19 			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.52+0af3f5a719 			fabric-client-tags-api-v1: Fabric Client Tags 1.1.15+6573ed8c19 			fabric-command-api-v1: Fabric Command API (v1) 1.2.49+f71b366f19 			fabric-command-api-v2: Fabric Command API (v2) 2.2.28+6ced4dd919 			fabric-commands-v0: Fabric Commands (v0) 0.2.66+df3654b319 			fabric-content-registries-v0: Fabric Content Registries (v0) 8.0.18+b559734419 			fabric-convention-tags-v1: Fabric Convention Tags 2.1.2+7f945d5b19 			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.9.2+e60e56d419 			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.29+0af3f5a719 			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.4.0+da19b51a19 			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 20.2.24+16c4ae2519 			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.0+6fc22b9919 			fabric-entity-events-v1: Fabric Entity Events (v1) 1.7.0+2122d82819 			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.13+ba9dae0619 			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.53+6ced4dd919 			fabric-item-api-v1: Fabric Item API (v1) 11.1.1+d5debaed19 			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.1.6+6823f7cd19 			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.47+0af3f5a719 			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.45+df3654b319 			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.5.0+01d9a51c19 			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.15+3f89f5a519 			fabric-loot-api-v3: Fabric Loot API (v3) 1.0.3+3f89f5a519 			fabric-message-api-v1: Fabric Message API (v1) 6.0.13+6573ed8c19 			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 2.0.0+fe474d6b19 			fabric-networking-api-v1: Fabric Networking API (v1) 4.3.0+c7469b2119 			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 15.2.1+40875a9319 			fabric-particles-v1: Fabric Particles (v1) 4.0.2+6573ed8c19 			fabric-recipe-api-v1: Fabric Recipe API (v1) 5.0.13+6508971219 			fabric-registry-sync-v0: Fabric Registry Sync (v0) 5.2.0+34f5d91419 			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.4.0+c705a49c19 			fabric-renderer-indigo: Fabric Renderer - Indigo 1.7.0+c705a49c19 			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.68+df3654b319 			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.48+73761d2e19 			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.6+1daea21519 			fabric-rendering-v0: Fabric Rendering (v0) 1.1.71+df3654b319 			fabric-rendering-v1: Fabric Rendering (v1) 5.0.5+df16efd019 			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 4.3.0+8dc279b119 			fabric-resource-loader-v0: Fabric Resource Loader (v0) 1.3.1+5b5275af19 			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.25+8b68f1c719 			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.88+b559734419 			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.23+6573ed8c19 			fabric-transfer-api-v1: Fabric Transfer API (v1) 5.4.2+95bead5f19 			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.2.0+45b9699719 		fabric-language-kotlin: Fabric Language Kotlin 1.10.19+kotlin.1.9.23 		fabricloader: Fabric Loader 0.16.5 			mixinextras: MixinExtras 0.4.1 		ferritecore: FerriteCore 7.0.0 		forgeconfigapiport: Forge Config API Port 21.1.2 			com_electronwill_night-config_core: core 3.8.0 			com_electronwill_night-config_toml: toml 3.8.0 		gpumemleakfix: Gpu memory leak fix mod 1.21-1.8 		immediatelyfast: ImmediatelyFast 1.2.21+1.21.1 			net_lenni0451_reflect: Reflect 1.3.4 		inventoryessentials: Inventory Essentials 21.1.1 		iris: Iris 1.8.0-beta.3+mc1.21.1 			io_github_douira_glsl-transformer: glsl-transformer 2.0.1 			org_anarres_jcpp: jcpp 1.4.14 			org_antlr_antlr4-runtime: antlr4-runtime 4.13.1 		jade: Jade 15.3.4+fabric 		java: Java HotSpot(TM) 64-Bit Server VM 21 		jei: Just Enough Items 19.18.3.204 		lootr: Lootr 1.21-1.10.34.86 		magistuarmory: Epic Knights: Shields, Armor and Weapons 9.14 		mcwfurnitures: Macaw's Furniture 3.3.0 		medieval_buildings: Medieval Buildings 1.0.2 		minecraft: Minecraft 1.21.1 		minetiface: mInetiface 2.1.0 			com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.14.2 			com_fasterxml_jackson_core_jackson-core: jackson-core 2.14.2 			com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.14.2 			io_github_blackspherefollower_buttplug4j: buttplug4j 3.0.67 			jakarta_websocket_jakarta_websocket-api: jakarta.websocket-api 2.1.0 			minetiface-root_commons_: commons unspecified 			org_eclipse_jetty_jetty-alpn-client: jetty-alpn-client 10.0.14 			org_eclipse_jetty_jetty-client: jetty-client 10.0.14 			org_eclipse_jetty_jetty-http: jetty-http 10.0.14 			org_eclipse_jetty_jetty-io: jetty-io 10.0.14 			org_eclipse_jetty_jetty-jmx: jetty-jmx 10.0.14 			org_eclipse_jetty_jetty-util: jetty-util 10.0.14 			org_eclipse_jetty_jetty-xml: jetty-xml 10.0.14 			org_eclipse_jetty_toolchain_jetty-javax-websocket-api: jetty-javax-websocket-api 1.1.2 			org_eclipse_jetty_websocket_websocket-core-client: websocket-core-client 10.0.14 			org_eclipse_jetty_websocket_websocket-core-common: websocket-core-common 10.0.14 			org_eclipse_jetty_websocket_websocket-javax-client: websocket-javax-client 10.0.14 			org_eclipse_jetty_websocket_websocket-javax-common: websocket-javax-common 10.0.14 		modmenu: Mod Menu 11.0.2 		moonlight: Moonlight Lib 1.21-2.17.10 		moyai: Moyai 1.21-2.1.5 		mr_bucketable: Bucketable 3.3 		mr_dragonkind_evolved: Dragonkind Evolved | End Battle Reborn 1.5.3 		mr_enchantments_encore: Enchantments Encore 1.8 		mr_warfare_expanded: Warfare Expanded 1.5.1 		mru: Mineblock's Repeated Utilities 1.0.4+1.21+fabric 		naturescompass: Nature's Compass 1.21.1-2.2.5-fabric 		netherportalfix: NetherPortalFix 21.1.1 		niftycarts: NiftyCarts 21.0.1 		notenoughanimations: NotEnoughAnimations 1.7.6 		now-playing: Now Playing 1.5.6 		org_jetbrains_annotations: annotations 23.0.0 		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.9.23 		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.9.23 		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.9.23 		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.9.23 		org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.23.2 		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.0 		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.0 		org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.5.0 		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3 		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3 		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3 		owo: o?o 0.12.15+1.21 			io_wispforest_endec: endec 0.1.5 			io_wispforest_endec_gson: gson 0.1.3 			io_wispforest_endec_jankson: jankson 0.1.3 			io_wispforest_endec_netty: netty 0.1.2 		packetfixer: Packet Fixer 1.4.2 		phases-discord-rich-presence: Phase's Discord Rich Presence 1.5.0-1.21 			club_minnced_discord-rpc-release: discord-rpc-release v3.3.0 			com_github_minndevelopment_java-discord-rpc: java-discord-rpc v2.0.2 			midnightlib: MidnightLib 1.6.3 		placeholder-api: Placeholder API 2.4.1+1.21 		playeranimator: Player Animator 2.0.0-alpha1+1.21 		polymer-bundled: Polymer 0.9.18+1.21.1 			polymer-blocks: Polymer (Textured Blocks) 0.9.18+1.21.1 			polymer-common: Polymer (Common) 0.9.18+1.21.1 				packet_tweaker: Packet Tweaker 0.5.5+1.21 			polymer-core: Polymer (Core) 0.9.18+1.21.1 				polymer-networking: Polymer (Networking) 0.9.18+1.21.1 				polymer-registry-sync-manipulator: Polymer (Registry Sync Manipulator) 0.9.18+1.21.1 			polymer-resource-pack: Polymer (Resource Pack) 0.9.18+1.21.1 			polymer-virtual-entity: Polymer (Virtual Entity) 0.9.18+1.21.1 		puzzleslib: Puzzles Lib 21.1.22 		randomvillagenames: Random Village Names 3.7 		rolling_down_in_the_deep: Rolling Down in the Deep 0.2.0+1.21 		shouldersurfing: Shoulder Surfing Reloaded 4.4.1 		snowballsfreezemobs: Snowballs Freeze Mobs 3.7 		sodium: Sodium 0.6.0-beta.1+mc1.21 		sodium-extra: Sodium Extra 0.6.0-beta.1+mc1.21.1 			com_lodborg_interval-tree: interval-tree 1.0.0 		souper_secret_settings: Souper Secret Settings 1.0.9-mc1.21+ 		t_and_t: Towns and Towers 1.13.2 		tectonic: Tectonic 2.4.1a 		torohealth: ToroHealth Damage Indicators 1.21.1-fabric-1 		trade_cycling: Trade Cycling 1.21.1-1.0.15 		trashslot: TrashSlot 21.1.1 		treechop: HT's TreeChop 0.19.2 		trinkets: Trinkets 3.10.0 			cardinal-components-base: Cardinal Components API (base) 6.1.0 			cardinal-components-entity: Cardinal Components API (entities) 6.1.0 		universalcraft: UniversalCraft 362 		vigilance: Vigilance 306 		visualworkbench: Visual Workbench 21.1.0 		voicechat: Simple Voice Chat 1.21.1-2.5.22 		watut: What Are They Up To 1.21.0-1.1.3 		weaponmod: Balkon's WeaponMod: Legacy 1.22.4 		wover: WorldWeaver 21.0.13 			wover-biome: WorldWeaver - Biome API 21.0.13 			wover-block: WorldWeaver - Block and Item API 21.0.13 			wover-common: WorldWeaver - Common API 21.0.13 			wover-core: WorldWeaver - Core API 21.0.13 			wover-datagen: WorldWeaver - Datagen API 21.0.13 			wover-events: WorldWeaver - Events API 21.0.13 			wover-feature: WorldWeaver - Feature API 21.0.13 			wover-generator: WorldWeaver - World Generator API 21.0.13 			wover-item: WorldWeaver - Item API 21.0.13 			wover-math: WorldWeaver - Math API 21.0.13 			wover-preset: WorldWeaver - World Preset API 21.0.13 			wover-recipe: WorldWeaver - Recipe API 21.0.13 			wover-structure: WorldWeaver - Structure API 21.0.13 			wover-surface: WorldWeaver - Surface API 21.0.13 			wover-tag: WorldWeaver - Tag API 21.0.13 			wover-ui: WorldWeaver - UI API 21.0.13 			wunderlib: WunderLib 21.0.8 		xaerominimap: Xaero's Minimap 24.4.0 		xaeroworldmap: Xaero's World Map 1.39.0 	Loaded Shaderpack: (off) 	Server Running: true 	Player Count: 2 / 8; [class_3222['xrendermanx'/23, l='ServerLevel[New World]', x=-666.09, y=85.94, z=710.27], class_3222['Goose_805'/891, l='ServerLevel[New World]', x=-666.09, y=85.94, z=707.62]] 	Active Data Packs: vanilla, fabric, armorful, balm-fabric (incompatible), bclib, bettercombat, betterend, carryon (incompatible), collective, combat-plus-core, deeperdarker (incompatible), dualswords, elytraslot (incompatible), explorerscompass, fabric-convention-tags-v2, lootr, magistuarmory, mcwfurnitures (incompatible), medieval_buildings (incompatible), moonlight, moyai, mr_bucketable, mr_dragonkind_evolved, mr_enchantments_encore, mr_warfare_expanded, naturescompass, niftycarts, t_and_t, treechop, trinkets, visualworkbench (incompatible), weaponmod, wover-generator, wover-preset, wover-surface, wover-tag, tectonic:tectonic, $polymer-resources, moonlight:mods_dynamic_assets 	Available Data Packs: $polymer-resources, armorful, balm-fabric (incompatible), bclib, bettercombat, betterend, betterend:nourish_extensions, betterend:patchouli_extensions, bundle, carryon (incompatible), collective, combat-plus-core, deeperdarker (incompatible), dualswords, elytraslot (incompatible), explorerscompass, fabric, fabric-convention-tags-v2, lootr, magistuarmory, mcwfurnitures (incompatible), medieval_buildings (incompatible), moonlight, moonlight:mods_dynamic_assets, moyai, mr_bucketable, mr_dragonkind_evolved, mr_enchantments_encore, mr_warfare_expanded, naturescompass, niftycarts, t_and_t, tectonic:tectonic, trade_rebalance, treechop, trinkets, vanilla, visualworkbench (incompatible), weaponmod, wover-generator, wover-preset, wover-surface, wover-tag 	Enabled Feature Flags: minecraft:vanilla 	World Generation: Experimental 	World Seed: -3205059962823751810 	Type: Integrated Server (map_client.txt) 	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric' 	Launched Version: 1.21.1 #@!@# Game crashed! Crash report saved to: #@!@# C:\Users\AppData\Roaming\PrismLauncher\instances\not a zip bomb and em is gay\.minecraft\crash-reports\crash-2024-12-07_16.01.28-server.txt Process exited with code -1.

### Additional Comments

does not occur when attacking mobs, multiplayer was P2P via Essential, only server host experiences crash

### Conclusion

- [ ] I agree that I am inattentively reading the description, just filling out everything

**Comment by GamesLuk** [comment]
Same Error on 1.21.1 Neoforge

**Comment by Magistu** [comment]
duplicate of https://github.com/Magistu/Epic-Knights/issues/60
